### ISSUE TITLE
[FEATURE] MainHome 화면 UI 작업

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#12]
## 내용
- MainHome 화면 작업 - HomeFragment

## ToDo
- [x] 메인 홈 화면 UI
- [x] 약속 생성 or 방 입장 선택 화면 UI
- [x] 약속이 없을 때 나오는 화면 UI
