### ISSUE TITLE
[FEATURE] 장소 입력 화면 - 추가 세부 기능

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#16]
## 내용
- 장소 입력 화면에서 추가적으로 필요한 기능

## ToDo
- [x] 장소 추가하면 EditText 초기화하는 기능
- [x] 장소 추가시 앞뒤 공백 제거
- [x] 동일한 장소 (String == String) 일 때는 추가를 막는 기능
- [x] 장소 추가 버튼 - 장소명 입력에 따라 이미지 변경
- [x] 추가한 장소 삭제 기능
- [x] 자신이 선택한 장소가 없으면 '스킵할래요' , 있으면 '다음' 출력 기능
