### ISSUE TITLE
[FEATURE] Main Room 화면 UI

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#19]
## 내용
- MainRoom (특정 약속방) 화면 UI 및 Interaction

## ToDo
- [x] MainRoom 기본 화면
- [x] 언제 or 어디서 결과 확인 화면
- [x] 약속방 명단 화면 (디자인 나오면)

**Comment by eshc123** [comment]
이번 이슈도 나눠서 진행할게요..! MainRoom/언제어디서 와 약속방 명단 화면/interaction 으로 나누겠습니다.
