### ISSUE TITLE
[FEATURE] 패키지 구조 및 인터페이스 작업

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#2]
## 내용
- 프로젝트 패키지 구조 잡고 인터페이스 생성

## ToDo
- [x] 아키텍처에 맞게 패키지 구조 잡기
- [x] 데이터 레이어 - 인터페이스 만들기
- [x] 도메인 레이어 - UseCase 도입 의논
