### ISSUE TITLE
[FEATURE] Input 화면 디자인 변경 반영 및 수정사항

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#33]
## 내용
- Input 화면 디자인 변경 반영 및 수정사항

## ToDo
- [x] 코드, 이름, 방이름 입력 화면 이미지 추가
- [x] 최소 인원 숫자 TextView 크기 고정
- [x] 장소 입력 앞에서 추가
- [x] 장소, 시간대 아이템 margin 추가
- [x] 약속방 완료 화면 이미지 추가 및 뷰 변경
- [x] 약속방 완료 화면 클립보드 복사 기능  추가
