### ISSUE TITLE
[FEATURE] Firebase 세팅

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#4]
## 내용
- fcm 을 위한 firebase 세팅

## ToDo
- [x] Firebase 구성 파일 추가 (로컬)
- [x] Firebase SDK 추가 
- [x] Firebase SDK 적용시점에서 token 값 확인 가능 검토
