### ISSUE TITLE
[FEATURE] 방 만들기 화면 수정 사항

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#45]
## 내용
- 방 만들기 화면 수정 사항

## ToDo
- [ ] EditText focusing (방 진입 했을때 키보드 나타나기)
- [ ] 달력 디자인 및 세부 사항 수정
- [ ] 날짜 시간 디자인 및 세부 사항 수정
- [ ] 장소 목록 위치 바꾸기
