### ISSUE TITLE
[FEATURE] 방 상세 화면 수정 사항

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#48]
## 내용
- 방 상세 화면 수정 사항

## ToDo
- [x] 목록 디테일 수정
- [x] 방 상태별 버튼 update
- [x] 관련 API 추가 및 수정
