### ISSUE TITLE
[FEATURE] 홈 화면 FAB 개선

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#80]
## 내용
- 홈 화면 FAB 개선

## ToDo
- [ ] FAB 클릭 시 배경 어둡게 하기 (status bar 포함)
- [ ] 배경 클릭 하면 FAB dismisss/cancel 처리 (열렸던 버튼들 닫히고 배경 다시 밝아지게)
- [ ] 클릭 후 화면 이동하고 다시 돌아와서 버튼을 다시 클릭하면 열리지 않는 문제 수정
- [ ] 버튼 클릭 시 새로운 약속 생성하기 올라오는 위치 조정

#참고사항
- 이해 안가는 부분이나 화면이 필요한 부분 있으면 comment나 슬랙 DM 보내주세요!
