### ISSUE TITLE
[FEATURE] 약속방 상세화면 개선사항

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#81]
## 내용
- 약속방 상세화면 개선사항

## ToDo
- [x] 방 상세 - 어디서 투표 후 화면 전환 혹은 선택 막기
- [x] 방 상세 UI 개선
  - [x] 상단 뷰 elevation
  - [x] status bar , 상단뷰 color 동일하게
