### ISSUE TITLE
[FEATURE] 메인 홈, 생성/참여 단계, 방 상세 화면 수정

### ISSUE THREAD

**Issue by eshc123** [Nexters/www-android#85]
## 내용
- 메인 홈, 생성/참여 단계, 방 상세 화면 수정

## ToDo
- [x] 메인 홈 탭 텍스트 크기 수정
- [x] 닉네임, 방이름 아이콘 constraint 수정
- [x] 인원 수 텍스트 width 수정
- [x] 메인 홈 d-day 수정
- [x] 방 상세 버튼 마진 수정
